//crawl
Given(/^they run the accessibility validator command (?!with auth)(.*)$/, async (url) => {
  await pageObjects.a11yValidation.runA11yCrawlOnly(url);
});

Given(/^they run the accessibility validator on page (.+)$/, async (pageUrl) => {
  await pageObjects.a11yValidation.runA11yOnSinglePage(pageUrl.trim());
});

Given(/^they run the accessibility validator on pages from csv file "([^"]+)"$/, async (relativeCsvPath) => {
  await pageObjects.a11yValidation.runA11yOnPagesFromFile(relativeCsvPath);
});

Given(/^they run the accessibility validator command with auth (.*)$/, async (url) => {
  await pageObjects.a11yValidation.runA11yCrawlWithAuth(url);
});

Given(
  /^they run the accessibility validator by crawling public from (.*) then validating private page (.*)$/,
  async (publicStartUrl, privateUrl) => {
    await pageObjects.a11yValidation.runA11yPublicThenPrivate(publicStartUrl, privateUrl);
  }
);

Given(/^they run the accessibility validator on pages from csv file with auth "([^"]+)"$/, async (relativeCsvPath) => {
  await pageObjects.a11yValidation.runA11yOnPagesFromFileWithAuth(relativeCsvPath);
});

Then(/^the accessibility crawl results should be generated$/, async () => {
  // Reports are generated by the validator itself; if the Given step completes without throwing,
  // treat that as success for this example project.
});
